### ISSUE TITLE
IOError: file `sorted_gaps.L.bam` not found

### ISSUE THREAD

**Issue by dbrowneup** [dbrowneup/Jelly2#1]
Jelly2 test #7 failed after successfully running BLASR alignments against left and right flanks. There appears to be a problem with the code wrapping samtools sort.

```
[dbrowne@ada3 2017.05.09_Jelly2_Testing]$ cat OUT_JELLY2_TESTING_v7 
[INFO] 2017-05-09T22:59:48 [blasr] started.
[INFO] 2017-05-10T02:00:05 [blasr] ended.
[INFO] 2017-05-10T02:00:05 [blasr] started.
[INFO] 2017-05-10T05:00:01 [blasr] ended.
open: No such file or directory
[bam_sort_core] fail to open file sorted_gaps.L.bam
open: No such file or directory
[bam_sort_core] fail to open file sorted_gaps.R.bam
open: No such file or directory
[bam_index_build2] fail to open the BAM file.
open: No such file or directory
[bam_index_build2] fail to open the BAM file.
Traceback (most recent call last):
  File "Jelly2.py", line 94, in <module>
    main()
  File "Jelly2.py", line 85, in main
    support.find_support(args)
  File "/scratch/user/dbrowne/Software/Jelly2/src/Support.py", line 42, in find_support
    gapsL = pysam.AlignmentFile('sorted_gaps.L.bam', 'rb')
  File "pysam/libcalignmentfile.pyx", line 397, in pysam.libcalignmentfile.AlignmentFile.__cinit__ (pysam/libcalignmentfile.c:5831)
  File "pysam/libcalignmentfile.pyx", line 558, in pysam.libcalignmentfile.AlignmentFile._open (pysam/libcalignmentfile.c:7556)
IOError: file `sorted_gaps.L.bam` not found

------------------------------------------------------------
Sender: LSF System <lsfadmin@nxt1356>
Subject: Job 5569273: <JELLY2_TESTING_v7> in cluster <Main_Compute> Exited

Job <JELLY2_TESTING_v7> was submitted from host <login3> by user <dbrowne> in cluster <Main_Compute>.
Job was executed on host(s) <20*nxt1356>, in queue <sn_long>, as user <dbrowne> in cluster <Main_Compute>.
</home/dbrowne> was used as the home directory.
</scratch/user/dbrowne/2017.05_MAY/2017.05.09_Jelly2_Testing> was used as the working directory.
Started at Tue May  9 22:59:39 2017
Results reported on Wed May 10 05:00:02 2017

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
#BSUB -J JELLY2_TESTING_v7 -L /bin/bash -W 40:00
#BSUB -n 20 -R "span[ptile=20] rusage[mem=2700] select[nxt]" -M 2700
#BSUB -o OUT_JELLY2_TESTING_v7
##
# Load required modules
ml Biopython/1.68-intel-2016b-Python-2.7.12
ml SAMtools/1.3.1-intel-2016b
# Add python libraries for Jelly2, pysam, pyfaidx
export PYTHONPATH="$PYTHONPATH:/scratch/user/dbrowne/Software/Jelly2/src:/scratch/user/dbrowne/Software/lib/python2.7/site-packages"
# Load BLASR
export LD_LIBRARY_PATH=/scratch/user/dbrowne/Software/pitchfork/deployment/lib:$LD_LIBRARY_PATH
export PATH=/scratch/user/dbrowne/Software/pitchfork/deployment/bin:$PATH
# Load Minimap, Miniasm, Racon
export PATH=/scratch/user/dbrowne/Software/minimap:/scratch/user/dbrowne/Software/miniasm:/scratch/user/dbrowne/Software/pitchfork/deployment/bin:$PATH
#
cd /scratch/user/dbrowne/2017.05_MAY/2017.05.09_Jelly2_Testing
#
python Jelly2.py -t 20 -b "--minSubreadLength 10000" Scaffolds_Q60HQ_1Mb.fa PACBIO_Reads_ALL.bam

------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   57429.12 sec.
    Max Memory :                                 326 MB
    Average Memory :                             195.18 MB
    Total Requested Memory :                     54000.00 MB
    Delta Memory :                               53674.00 MB
    Max Swap :                                   1 MB
    Max Processes :                              5
    Max Threads :                                29

The output (if any) is above this job summary.
```

Note: approximately half of the PacBio subreads >10kb were aligned to the flanks. May want to tighten up BLASR alignment parameters to improve run time and reduce noise.

**Comment by dbrowneup** [comment]
I finally fixed this bug after much frustration by simply switching the sort operation to `pysam.sort` instead of using my own subprocess wrapper around samtools
