### ISSUE TITLE
QUAL values missing from BAM files, unable to write FastQ

### ISSUE THREAD

**Issue by dbrowneup** [dbrowneup/Jelly2#2]
Finally got everything working to the point where the program attempts to load QUAL values associated with the gap-bridging sequence. However, there are no QUAL values in the original PacBio BAM files. I have opened an issue with PacBio (https://github.com/PacificBiosciences/PacBioFileFormats/issues/50) to try and get this resolved.

```
[dbrowne@ada8 2017.05.09_Jelly2_Testing]$ cat OUT_JELLY2_TESTING_v21 
Found save point: support
Number of gaps loaded in gap_list: 38
6 gaps loaded for scaffold Contig17_1_1011970_pilon|arrow
Scaffold: Contig17_1_1011970_pilon|arrow Gap: 1 Size: 2509 Support: 0
Scaffold: Contig17_1_1011970_pilon|arrow Gap: 2 Size: 4400 Support: 0
Scaffold: Contig17_1_1011970_pilon|arrow Gap: 3 Size: 8609 Support: 97
Read Span: -5054
Read Span: 7754
Traceback (most recent call last):
  File "Jelly2.py", line 125, in <module>
    main()
  File "Jelly2.py", line 103, in main
    support.find_support(args)
  File "/scratch/user/dbrowne/Software/Jelly2/src/Support.py", line 79, in find_support
    quality = L.query_qualities[L.query_alignment_end:R.query_alignment_start]
TypeError: 'NoneType' object has no attribute '__getitem__'

------------------------------------------------------------
Sender: LSF System <lsfadmin@nxt1527>
Subject: Job 5689987: <JELLY2_TESTING_v21> in cluster <Main_Compute> Exited

Job <JELLY2_TESTING_v21> was submitted from host <login8> by user <dbrowne> in cluster <Main_Compute>.
Job was executed on host(s) <20*nxt1527>, in queue <sn_long>, as user <dbrowne> in cluster <Main_Compute>.
</home/dbrowne> was used as the home directory.
</scratch/user/dbrowne/2017.05_MAY/2017.05.09_Jelly2_Testing> was used as the working directory.
Started at Thu May 11 15:50:04 2017
Results reported on Thu May 11 15:50:35 2017

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
#BSUB -J JELLY2_TESTING_v21 -L /bin/bash -W 40:00
#BSUB -n 20 -R "span[ptile=20] rusage[mem=2700] select[nxt]" -M 2700
#BSUB -o OUT_JELLY2_TESTING_v21
##
# Load Python, SAMtools
ml Python/2.7.12-intel-2016b
ml SAMtools/1.3.1-intel-2016b
# Load Jelly2, pysam, pyfaidx
export PYTHONPATH=$PYTHONPATH:/scratch/user/dbrowne/Software/Jelly2/src:/scratch/user/dbrowne/Software/lib/python2.7/site-packages
# Load BLASR
export LD_LIBRARY_PATH=/scratch/user/dbrowne/Software/pitchfork/deployment/lib:$LD_LIBRARY_PATH
export PATH=/scratch/user/dbrowne/Software/pitchfork/deployment/bin:$PATH
# Load Minimap, Miniasm, Racon
export PATH=/scratch/user/dbrowne/Software/racon/bin:/scratch/user/dbrowne/Software/minimap:/scratch/user/dbrowne/Software/miniasm:$PATH
#
cd /scratch/user/dbrowne/2017.05_MAY/2017.05.09_Jelly2_Testing
#
python Jelly2.py -t 20 -d 2 -b "--minSubreadLength 10000 --minAlnLength 200 --maxScore -1000" \
    Scaffolds_Q60HQ_1Mb.fa \
    PACBIO_Reads_ALL.bam

------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   28.77 sec.
    Max Memory :                                 2499 MB
    Average Memory :                             1419.20 MB
    Total Requested Memory :                     54000.00 MB
    Delta Memory :                               51501.00 MB
    Max Processes :                              4
    Max Threads :                                5

The output (if any) is above this job summary.
```

**Comment by dbrowneup** [comment]
As a workaround to this issue, I deactivated the consensus module (Minimap/Racon) and made the program write FastA files instead of FastQ files. Thus the reads can still be assembled with Minimap/Miniasm, but no consensus will be generated. The gap-filled assembly can be polished with the likes of Arrow to get high-quality gap sequences.
